### ISSUE TITLE
Publishing to App Store

### ISSUE THREAD

**Issue by acmpo6ou** [avan1235/open-otp#16]
Are there plans to publish this to App Store? Very soon (at least in EU) it will be possible to side load apps, so you'll be able to publish it to a different app store, and won't need to pay for App Store fee.

**Comment by avan1235** [comment]
Yes, as soon as I don't have to pay Apple 99$/year, I'll publish the iOS version of OpenOTP.
But afaiu there will be many restrictions on sideloading, so we will see how smooth the process will be - check out for updates in nearest weeks/months

**Comment by acmpo6ou** [comment]
True, I'm also not sure what to expect yet. I think they will have alternative app stores. Maybe there will be a store for open source apps. Like F-Droid on Android. But sideloading will be allowed very soon like in 2 weeks I think.

**Comment by avan1235** [comment]
I'll close this issue with proper reference as soon as it's implemented on `master`, so you get the update.

**Comment by acmpo6ou** [comment]
iOS 17.4 is out and it brings support for alternative App Stores! But I'm not sure if there is a nice App Store for open source apps. I'm not even sure which app stores exist.

**Comment by acmpo6ou** [comment]
Hello! Here is a Free (only 1.5 euros/year) and Open Source alternative AppStore where you can publish your app! https://fosstodon.org/@altstore/112287538562764439
